WeatherApp/urls.py
from django.urls import path
from . import views

app_name = 'WeatherApp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('current', views.Current, name='current'),
    path('delete_current/<pk>/', views.WeatherCurrentDeleteView.as_view(), name='delete_current_city'),
    path('hourly', views.Hourly, name='hourly'),
    path('delete_hourly/<pk>/', views.WeatherHourlyDeleteView.as_view(), name='delete_hourly_city'),
    path('average', views.Average, name='average'),
    path('delete_average/<pk>/', views.WeatherAverageDeleteView.as_view(), name='delete_average_city'),
    path('max_min', views.Max_Min, name='max_min'),
    path('delete_max_min/<pk>/', views.Weather_Max_Min_DeleteView.as_view(), name='delete_max_min_city'),
    path('grapics', views.Bar_Chart, name='graphics')
]

WeatherProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WeatherApp.urls')),
]

WeatherApp/models.py
from django.db import models


class City(models.Model):
    Id = models.AutoField(primary_key=True)
    Address = models.CharField(max_length=25)
    Dt = models.PositiveIntegerField()

    def __str__(self):
        return self.Address

    class Meta:
        verbose_name_plural = 'cities'

WeatherApp/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import City


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['Address', 'Dt']
        widgets = {'Address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City Name'}),
                   'Dt': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'TimeStamp'}),
                }

WeatherApp/views.py
from django.shortcuts import render
import requests
from geopy.geocoders import Nominatim
from .forms import CityForm
from .models import City
from django.views.generic import DeleteView, TemplateView
from django.urls import reverse_lazy
import datetime
import json


class IndexView(TemplateView):
    template_name = 'Base.html'


def Current(request):
    url = "https://community-open-weather-map.p.rapidapi.com/onecall/timemachine"
    url_second = "https://community-open-weather-map.p.rapidapi.com/weather"
    form = CityForm()
    Error_message = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)  # Handling form request

        if form.is_valid():
            New_City = form.cleaned_data['Address']
            New_Dt = form.cleaned_data['Dt']
            Existing_City = City.objects.filter(Address=New_City).count()
            if Existing_City == 0:
                querystring = {"callback": "test", "id": "2172797", "units": "%22metric%22 or %22imperial%22",
                               "mode": "xml%2C html", "q": New_City}

                headers = {
                    'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
                    'x-rapidapi-key': "6446924734mshd20c29c9014fd63p155d13jsnc1cdd0345c05"
                }

                response = requests.request("GET", url_second, headers=headers, params=querystring)
                if response.status_code == 200:
                    form.save()
                else:
                    Error_message = 'City does not exist in the world'

            else:
                Error_message = 'City already exists in the database'

        if Error_message:
            message = Error_message
            message_class = 'alert alert-danger'
        else:
            message = 'City added successfully'
            message_class = 'alert alert-success'

    Cities = City.objects.all()
    Current_List = []

    for city in Cities:

        # Get the coordinates of address of the city
        Geolocator = Nominatim(user_agent="Lucas")
        Location = Geolocator.geocode(city.Address)
        Coordinates = []
        Latitude = Location.latitude
        Longitude = Location.longitude
        Coordinates.append(Latitude)
        Coordinates.append(Longitude)
        #############################################################################
        querystring = {"lat": Coordinates[0], "lon": Coordinates[1], "dt": city.Dt}

        headers = {
            'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
            'x-rapidapi-key': "6446924734mshd20c29c9014fd63p155d13jsnc1cdd0345c05"
        }
        # Get all the features of this particular city, in the last 24 hours
        response = requests.request("GET", url, headers=headers, params=querystring)

        data = response.json()

        # Get only the current features of this particular city and put it in a dictionary
        Current_Dict = {
            'Id': city.Id,
            'City': city.Address,
            'Date': datetime.datetime.fromtimestamp(data['current']['dt']).strftime('%Y-%m-%d %H:%M:%S'),
            'Temperature': data['current']['temp'],
            'Humidity': data['current']['humidity'],
            'Wind_Speed': data['current']['wind_speed'],
            'Pressure': data['current']['pressure'],
            'Icon': data['current']['weather'][0]['icon'],
        }

        Current_List.append(Current_Dict)
    context = {'Current_List': Current_List, 'form': form, 'message': message, 'message_class': message_class}

    return render(request, 'WeatherApp/Current_Weather.html', context)


class WeatherCurrentDeleteView(DeleteView):
    model = City
    context_object_name = "Wd"
    template_name = "WeatherApp/Weather_current_confirm_delete.html"
    success_url = reverse_lazy("WeatherApp:current")


def Hourly(request):
    url = "https://community-open-weather-map.p.rapidapi.com/onecall/timemachine"
    url_second = "https://community-open-weather-map.p.rapidapi.com/weather"
    form = CityForm()
    Error_message = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)  # Handling form request

        if form.is_valid():
            New_City = form.cleaned_data['Address']
            Existing_City = City.objects.filter(Address=New_City).count()
            if Existing_City == 0:
                querystring = {"callback": "test", "id": "2172797", "units": "%22metric%22 or %22imperial%22",
                               "mode": "xml%2C html", "q": New_City}

                headers = {
                    'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
                    'x-rapidapi-key': "6446924734mshd20c29c9014fd63p155d13jsnc1cdd0345c05"
                }

                response = requests.request("GET", url_second, headers=headers, params=querystring)
                if response.status_code == 200:
                    form.save()
                else:
                    Error_message = 'City does not exist in the world'

            else:
                Error_message = 'City already exists in the database'

        if Error_message:
            message = Error_message
            message_class = 'alert alert-danger'
        else:
            message = 'City added successfully'
            message_class = 'alert alert-success'

    Cities = City.objects.all()
    Hourly_List = []

    for city in Cities:
        Hourly_Dict = {}

        # Get the coordinates of address of the city
        Geolocator = Nominatim(user_agent="Lucas")
        Location = Geolocator.geocode(city.Address)
        Coordinates = []
        Latitude = Location.latitude
        Longitude = Location.longitude
        Coordinates.append(Latitude)
        Coordinates.append(Longitude)
        #############################################################################
        querystring = {"lat": Coordinates[0], "lon": Coordinates[1], "dt": city.Dt}

        headers = {
            'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
            'x-rapidapi-key': "6446924734mshd20c29c9014fd63p155d13jsnc1cdd0345c05"
        }
        # Get all the features of this particular city, in the last 24 hours
        response = requests.request("GET", url, headers=headers, params=querystring)

        data = response.json()
        # Get only the hourlies features of this particular city and put it in a dictionary

        hourly = data['hourly']
        for i in range(0, len(hourly)):
            Hourly_Dict["Horario{}".format(i)] = datetime.datetime.fromtimestamp(hourly[i]['dt']).strftime('%Y-%m-%d %H:%M:%S')
            Hourly_Dict["Temperature{}".format(i)] = hourly[i]['temp']
            Hourly_Dict["Humidity{}".format(i)] = hourly[i]['humidity']
            Hourly_Dict["Wind_speed{}".format(i)] = hourly[i]['wind_speed']
            Hourly_Dict["Pressure{}".format(i)] = hourly[i]['pressure']
            Hourly_Dict["Icon{}".format(i)] = hourly[i]['weather'][0]['icon']

        Hourly_Dict["Address"] = city.Address
        Hourly_Dict["Id"] = city.Id
        Hourly_List.append(Hourly_Dict)

    context = {'Hourly_List': Hourly_List, 'form': form, 'message': message, 'message_class': message_class}

    return render(request, 'WeatherApp/Hourly_Weather.html', context)


class WeatherHourlyDeleteView(DeleteView):
    model = City
    context_object_name = "Wd"
    template_name = "WeatherApp/Weather_hourly_confirm_delete.html"
    success_url = reverse_lazy("WeatherApp:hourly")


def Average(request):
    url = "https://community-open-weather-map.p.rapidapi.com/onecall/timemachine"
    url_second = "https://community-open-weather-map.p.rapidapi.com/weather"
    form = CityForm()
    Error_message = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)  # Handling form request

        if form.is_valid():
            New_City = form.cleaned_data['Address']
            Existing_City = City.objects.filter(Address=New_City).count()
            if Existing_City == 0:
                querystring = {"callback": "test", "id": "2172797", "units": "%22metric%22 or %22imperial%22",
                               "mode": "xml%2C html", "q": New_City}

                headers = {
                    'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",
                    'x-rapidapi-key': "6446924734mshd20c29c9014fd63p155d13jsnc1cdd0345c05"
                }

                response = requests.request("GET", url_second, headers=headers, params=querystring)
                if response.status_code == 200:
                    form.save()
                else:
                    Error_message = 'City does not exist in the world'

            else:
                Error_message = 'City already exists in the database'

        if Error_message:
            message = Error_message
            message_class = 'alert alert-danger'
        else:
            message = 'City added successfully'
            message_class = 'alert alert-success'

    Cities = City.objects.all()

    Average_List = []

    for city in Cities:
        Sum_Temperature = 0
        Sum_humidity = 0
        Sum_speedwind = 0
        Sum_pressure = 0
        Average_Dict = {}

        # Get the coordinates of address of the city
        Geolocator = Nominatim(user_agent="Lucas")
        Location = Geolocator.geocode(city.Address)
        Coordinates = []
        Latitude = Location.latitude
        Longitude = Location.longitude
        Coordinates.append(Latitude)
        Coordinates.append(Longitude)
        #############################################################################
        querystring = {"lat": Coordinates[0], "lon": Coordinates[1], "dt": city.Dt}

        headers = {
            'x-rapidapi-host': "community-open-weather-map.p.rapidapi.com",

WeatherApp/templates/WeatherApp/Average_Weather.html
{% extends "WeatherApp/Current_Weather.html" %}

{% block content %}
    <div class="container">
        <div class="row">
        <div class="col-lg-12">
    <form class="post-form" width=200px method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <br>
        <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>City</th>
                        <th>Temperature´s average</th>
                        <th>Humidity´s average</th>
                        <th>Wind Speed´s average</th>
                        <th>Pressure´s average</th>
                    </tr>
                </thead>
                <tbody>
                    {% for Average_Dict in Average_List %}
                            <tr>
                                <td>{{ Average_Dict.Id }}</td>
                                <td>{{ Average_Dict.Address }}</td>
                                <td>{{ Average_Dict.Temperature_average }} ºF</td>
                                <td>{{ Average_Dict.Humidity_average }} %</td>
                                <td>{{ Average_Dict.WindSpeed_average }} Km/h</td>
                                <td>{{ Average_Dict.Pressure_average }} hPa</td>
                                <td><a class="btn btn-danger" href="{% url 'WeatherApp:delete_average_city' Average_Dict.Id %}" role="button">Delete</a></td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
        </div>
    </div>
{% endblock %}

WeatherApp/templates/WeatherApp/Base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Weather Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Weather.css' %}"/>
<!-- CDN from MDB 4.19.1-->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
<!--CDN from MDB to javascript-->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</head>
<body>
<div class="content">
    <header class="header"> Welcome to Django Weather app </header>

    <div class="parallaxone"></div>
    <div style="height:150px;background-color:black;font-size:36px;color:white;font-weight: bold;">
        <h3><a href="{% url 'WeatherApp:current' %}">Current Weather</a></h3>
        <p>Here you can find four current weather features of any city. Enjoy this web page!!! </p>
    </div>

    <div class="parallaxtwo"></div>
    <div style="height:150px;background-color:black;font-size:36px;color:white;font-weight: bold;">
        <h3><a href="{% url 'WeatherApp:hourly' %}">Hourly Weather</a></h3>
        <p>Here you can find four hourlies weather features of any city. Enjoy this web page!!! </p>
    </div>

    <div class="parallaxthree"></div>
    <div style="height:150px;background-color:black;font-size:36px;color:white;font-weight: bold;">
        <h3><a href="{% url 'WeatherApp:average' %}">Weather Average</a></h3>
        <p>Here you can find the average of four weather features of the last 24 hours of any city. Enjoy this web page!!! </p>
    </div>

    <div class="parallaxfour"></div>
    <div style="height:150px;background-color:black;font-size:36px;color:white;font-weight: bold;">
        <h3><a href="{% url 'WeatherApp:max_min' %}">Max and Min Weather features</a></h3>
        <p>Here you can find the maximum and the minimum value of the four weather features in the last 24 hours of any city. Enjoy this web page!!! </p>
    </div>

    <div class="parallaxfive"></div>
    <div style="height:200px;background-color:black;font-size:36px;color:white;font-weight: bold;">
        <h3><a href="{% url 'WeatherApp:graphics' %}">Graphics</a></h3>
        <p>You can also have another option to view the behavior of climatic characteristics throughout the day. With our well-modeled and didactic graphics, you can effortlessly follow the daily weather history.</p>
    </div>
</div>

    <footer class="page-footer font-small mdb-color lighten-3 pt-4">
      <div class="container text-center text-md-left">
        <div class="row">

          <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
            <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 200px;">
            <p>Thank you for visit my website. Keep an eye here in my github profile to see more projects!!!</p>
          </div>
          <hr class="clearfix w-100 d-md-none">

          <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
            <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 200px;">
            <ul class="list-unstyled list-inline text-center">
                <li class="list-inline-item">
                    <a class="btn-floating btn-fb mx-1">
                        <i href="https://www.facebook.com/lucas.burigo.98" class="fab fa-facebook-f"> </i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/LC-burigo" class="btn-floating btn-gplus mx-1">
                        <i class="fab fa-github"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.linkedin.com/in/lucas-burigo-586243116/" class="btn-floating btn-li mx-1">
                        <i class="fab fa-linkedin-in"> </i>
                    </a>
                </li>
    <!--            <div style="font-size: 2rem;">-->
    <!--                <li class="list-inline-item">-->
    <!--                    <a class="btn-floating btn-gplus mx-1">-->
    <!--                        <div><i class="fab fa-facebook-f fa-fw blue-text"></i></div>-->
    <!--                    </a>-->
    <!--                </li>-->
    <!--                <li class="list-inline-item">-->
    <!--                    <a class="btn-floating btn-gplus mx-1">-->
    <!--                        <div><i class="fab fa-github fa-fw black-text"></i></div>-->
    <!--                    </a>-->
    <!--                </li>-->
    <!--                <li class="list-inline-item">-->
    <!--                    <a class="btn-floating btn-li mx-1">-->
    <!--                        <div><i class="fab fa-linkedin fa-fw blue-text"></i></div>-->
    <!--                    </a>-->
    <!--                </li>-->
    <!--            </div>-->
            </ul>
          </div>
        </div>
      </div>

      <div class="footer-copyright text-center py-3">Project created by: Lucas Búrigo</div>
    </footer>

    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</body>
</html>

WeatherApp/templates/WeatherApp/Current_Weather.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Weather Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Extends.css' %}"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.js"></script>
<!--Footer-->
    <link rel="stylesheet" type="text/css" media="screen" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

</head>
<body>
<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'WeatherApp:home' %}">Get any City Weather!!!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'WeatherApp:current' %}">Current Weather <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'WeatherApp:hourly' %}">Hourly Weather</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'WeatherApp:average' %}">Weather Average</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'WeatherApp:max_min' %}">Max and Min</a>
      </li>
      <li class="nav-item">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'WeatherApp:graphics' %}">Weather Graphics</a>
      </li>
      <li class="nav-item">
      <li class="nav-item">
        <a class="nav-link disabled" href="https://www.epochconverter.com/" tabindex="-1" aria-disabled="true">Epoch</a>
      </li>
    </ul>
  </div>
</nav>
{% block content %}
<div class="container">
    <div class="row">
    <div class="col-lg-12">
      <form class="post-form" width=200px method="POST">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="btn btn-primary">Save</button>
      </form>
      <div class="{{message_class}}" role="alert">{{message}}</div>
        <br>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>City</th>
                    <th>Date</th>
                    <th>Temperature</th>
                    <th>Humidity</th>
                    <th>Wind Speed</th>
                    <th>Pressure</th>
                    <th>Icon</th>
                </tr>
            </thead>
            <tbody>
                {% for Current_Dict in Current_List %}
                        <tr>
                            <td>{{ Current_Dict.Id }}</td>
                            <td>{{ Current_Dict.City }}</td>
                            <td>{{ Current_Dict.Date }}</td>
                            <td>{{ Current_Dict.Temperature }} ºF</td>
                            <td>{{ Current_Dict.Humidity }} %</td>
                            <td>{{ Current_Dict.Wind_Speed }} Km/h</td>
                            <td>{{ Current_Dict.Pressure }} hPa</td>
                            <td><img src="http://openweathermap.org/img/wn/{{ Current_Dict.Icon }}@2x.png" class="media-object" style="width:60px"></td>
                            <td><a class="btn btn-danger" href="{% url 'WeatherApp:delete_current_city' Current_Dict.Id %}" role="button">Delete</a></td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    </div>
</div>
{% endblock %}
<footer class="footer">
    <div id="copy-area">
      <div class="container">
        <div class="row">
            <div class="col-md-12">
              <p>Project created by: Lucas Búrigo</p>
            </div>
        </div>
      </div>
    </div>
  </footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

WeatherApp/templates/WeatherApp/Max_Min_Weather.html
{% extends "WeatherApp/Current_Weather.html" %}

{% block content %}
    <div class="container">
        <div class="row">
        <div class="col-lg-12">
    <form class="post-form" width=200px method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <br>
        <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>City</th>
                        <th>Max Temperature</th>
                        <th>Min Temperature</th>
                        <th>Max Humidity</th>
                        <th>Min Humidity</th>
                        <th>Max Wind Speed</th>
                        <th>Min Wind Speed</th>
                        <th>Max Pressure</th>
                        <th>Min Pressure</th>
                    </tr>
                </thead>
                <tbody>
                    {% for Max_Min_Dict in Max_Min_List %}
                            <tr>
                                <td>{{ Max_Min_Dict.Id }}</td>
                                <td>{{ Max_Min_Dict.Address }}</td>
                                <td>{{ Max_Min_Dict.Max_Temperature }}ºF</td>
                                <td>{{ Max_Min_Dict.Min_Temperature }}ºF</td>
                                <td>{{ Max_Min_Dict.Max_Humidity }}%</td>
                                <td>{{ Max_Min_Dict.Min_Humidity }}%</td>
                                <td>{{ Max_Min_Dict.Max_WindSpeed }}Km/h</td>
                                <td>{{ Max_Min_Dict.Min_WindSpeed }}Km/h</td>
                                <td>{{ Max_Min_Dict.Max_Pressure }}hPa</td>
                                <td>{{ Max_Min_Dict.Min_Pressure }}hPa</td>
                                <td><a class="btn btn-danger" href="{% url 'WeatherApp:delete_max_min_city' Max_Min_Dict.Id %}" role="button">Delete</a></td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
        </div>
    </div>
{% endblock %}